version: "3"

tasks:

  markdown:check-links:
    desc: Check for broken links
    deps:
      - task: npm:install-deps
    cmds:
      - |
        npx --package=markdown-link-check --call='
          STATUS=0
          for file in \
            $(find . -type d -name node_modules -prune -o -regex ".*[.]md" -print); do
            markdown-link-check \
              --quiet \
              --config "./.markdown-link-check.json" \
              "$file"
            STATUS=$(( $STATUS + $? ))
          done
          exit $STATUS
          '

  markdown:lint:
    desc: Check for problems in Markdown files
    deps:
      - task: npm:install-deps
    cmds:
      - npx markdownlint-cli "**/*.md"

  npm:install-deps:
    desc: Install dependencies managed by npm
    cmds:
      - npm install